name: gds
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build GDS
      uses: TinyTapeout/tt-gds-action@main

##############################################################
# Generate files for the 3D viewer

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    steps:
    - name: checkout GDS2glTF repo
      uses: actions/checkout@v3
      with:
        repository: mbalestrini/GDS2glTF

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: restore runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-runs-${{ github.run_id }}

    - name: gds2gltf
      run: |
        python -m pip install numpy gdspy triangle pygltflib
        cp runs/wokwi/results/final/gds/*.gds tinytapeout.gds
        python3 gds2gltf.py tinytapeout.gds

    - name: populate viewer cache
      uses: actions/cache@v3
      with:
        path: 'tinytapeout.gds.gltf'
        key: ${{ runner.os }}-viewer-${{ github.run_id }}

##############################################################
# Downloadable results from OpenLane

  artifact:
    needs:
    - gds
    runs-on: ubuntu-latest
    steps:
    - name: restore src cache
      uses: actions/cache@v3
      with:
        path: src
        key: ${{ runner.os }}-src-${{ github.run_id }}

    - name: restore runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-runs-${{ github.run_id }}

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          # path depends on the tag and the module name
          name: GDS
          path: |
            src/*
            runs/wokwi/results/final/*
            runs/wokwi/reports/metrics.csv
            runs/wokwi/reports/synthesis/1-synthesis.AREA 0.stat.rpt

##############################################################
# Publish to pages to get a nicely formatted result

  pages:
    needs:
    - viewer
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: restore png cache
      uses: actions/cache@v3
      with:
        path: 'gds_render.png'
        key: ${{ runner.os }}-png-${{ github.run_id }}
    - name: restore viewer cache
      uses: actions/cache@v3
      with:
        path: 'tinytapeout.gds.gltf'
        key: ${{ runner.os }}-viewer-${{ github.run_id }}
    - name: generate redirect to viewer
      run: |
        cat << EOF >> index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Redirecting to GDS Viewer...</title>
          </head>
          <body>
            <script>
              location.href = "https://gds-viewer.tinytapeout.com/?model=" + encodeURIComponent(location.href + '/tinytapeout.gds.gltf');
            </script>
          </body>
          </html>
        EOF
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1.2.2

##############################################################
# Add the 3D and 2D preview to the page

  preview:
    needs: pages
    runs-on: ubuntu-latest
    steps:
    - name: add gds preview
      run: |
        PAGE_URL=${{ needs.pages.outputs.page_url }}
        PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
        cat << EOF >> $GITHUB_STEP_SUMMARY
        # 3D Viewer
        [open 3D viewer](https://gds-viewer.tinytapeout.com/?model=$PAGE_URL/tinytapeout.gds.gltf)
        # 2D Preview
        ![png]($PAGE_URL/gds_render.png)
        EOF
