name: gds
# either manually started, or on a schedule
on: [push, workflow_dispatch]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@main

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@main
